apiVersion: v1
kind: Service
metadata:
    name: svc1
    labels:
        app: web
spec:
   type: NodePort
   ports:
    - port: 80
      protocol: TCP
      nodePort: 30080
   selector:
      app: web
